---
- name: get info on an address
  gcp_compute_address_info:
    region: "{{ region }}"
    filters:
    - "name = {{ hostname }}-address"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: address

- name: Add instance to inventory
  add_host:
    hostname: "{{ hostname }}"
    ansible_host: "{{ address.resources[0].address }}"
    ansible_user: "{{ user_name }}"
    ansible_ssh_private_key_file: "{{ ssh_key_dir }}{{ hostname }}"
    groups: server
