---
- name: Play local task
  hosts: localhost
  gather_facts: false
  vars:
    gcp_cred_kind: "serviceaccount"
  vars_files:
    - vars/create-instance-vars.yml
  tasks:
    - include_tasks: tasks/create-instance.yml
      name: Create GCP instance

- name: Play server task
  hosts: server
  become: true
  vars:
    dockerfile_path: "Docker/World"
  vars_files:
    - vars/run-server-vars.yml
  tasks:
    - include_tasks: tasks/run-server.yml
      name: Run minecraft server
