---
- name: Play local task
  hosts: localhost
  gather_facts: false
  vars:
    gcp_cred_kind: "serviceaccount"
  vars_files:
    - vars/create-instance-vars.yml
    - vars/playbook-vars.yml
  tasks:
    - include_tasks: tasks/create-instance.yml
      name: Create GCP instance
      when: exec_type == "create"
    - include_tasks: tasks/stop-instance.yml
      name: Stop GCP instance
      when: exec_type == "stop"
    - include_tasks: tasks/start-instance.yml
      name: Start GCP instance
      when: exec_type == "start"
    - include_tasks: tasks/delete-instance.yml
      name: Delete GCP instance
      when: exec_type == "delete"
    - include_tasks: tasks/add-hosts.yml
      name: Add hosts to inventory
      when: exec_type == "create" or exec_type == "download"

- name: Play server task
  hosts: server
  become: true
  vars:
    dockerfile_path: "Docker"
  vars_files:
    - vars/create-instance-vars.yml
    - vars/run-server-vars.yml
    - vars/playbook-vars.yml
  tasks:
    - include_tasks: tasks/run-server.yml
      name: Run minecraft server
      when: exec_type == "create"
    - include_tasks: tasks/download-world-data.yml
      name: Download world data
      when: exec_type == "download"
