name: prerelease RC apps
on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.EXT_GITHUB_PAT }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install wheel
      - name: Set releaser settings
        run: |
          git config --global user.name ${{ secrets.EXT_GITHUB_USER }}
          git config --global user.email ${{ secrets.EXT_GITHUB_EMAIL }}
      - name: Release
        run: |
          RELEASE_VERSION=$(poetry version -s)
          git tag ${RELEASE_VERSION}
          git push origin ${RELEASE_VERSION}
      - name: Build
        run: |
          poetry config repositories.test-pypi https://test.pypi.org/legacy/
          poetry config pypi-token.test-pypi "${{ secrets.TEST_PYPI_TOKEN }}"
          poetry build
          poetry publish -r test-pypi